### ISSUE TITLE
Allow oracle prices to be chained

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v3-periphery#199]
It may make sense to offer an interface for returning a quote in terms of token 3 from an amount of token 1 given prices for token 1/2 and token 2/3.

Investigation required re. the potential precision of a method like this.

**Comment by Yorkemartin** [comment]
Synthetix approached this problem here 

https://github.com/sohkai/uniswap-v3-spot-twap-oracle/blob/890dcde7f709158cb29bb09052e7323d4b7d33c1/contracts/DexPriceAggregatorUniswapV3.sol#L174-L212

**Comment by alejoamiras** [comment]
+1. I think is heavily understated how good the decentralized twaps are, and what they start allowing for the ecosystem.

**Comment by willhennessy** [comment]
update:  a version has been written in the swaprouter, but the generalized version remains to be written.
