### ISSUE TITLE
ExactInputParams is not up to date in this repo

### ISSUE THREAD

**Issue by TamtamHero** [Uniswap/v3-periphery#250]
This property https://github.com/Uniswap/v3-periphery/blob/main/contracts/interfaces/ISwapRouter.sol#L30 is gone in production on SwapRouter02 (see https://etherscan.io/address/0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45#code, and more precisiely here: https://etherscan.io/address/0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45#code#F15#L30)
I don't know if it is the sole difference, maybe there's more discrepancies ?
I couldn't find a 2.0.0 tag either.

**Comment by NoahZinsmeister** [comment]
the code for that router lives in https://github.com/Uniswap/swap-router-contracts!
