### ISSUE TITLE
Swap and Add Liquidity Atomically On-chain

### ISSUE THREAD

**Issue by jwenlee** [Uniswap/v3-periphery#251]
How do I realize this method directly in my intelligent contract? 
I saw a branch but there is no document tells me how to use it.(https://github.com/Uniswap/v3-periphery/tree/swap_and_add_the_sequel)

https://docs.uniswap.org/sdk/guides/liquidity/swap-and-add
Swap and Add Liquidity Atomically

**Comment by ibrahimkecici** [comment]
Hello. Can you find a solution?

**Comment by jwenlee** [comment]
Yes, I need to write my own contract to solve this problem. I can't find a better way.
