### ISSUE TITLE
Consult passes an invalid argument to IUniswapV3Pool.observe

### ISSUE THREAD

**Issue by Developer5600** [Uniswap/v3-periphery#258]
```
   uint32[] memory secondsAgos = new uint32[](2);
        secondsAgos[0] = secondsAgo;
        secondsAgos[1] = 0;

        (int56[] memory tickCumulatives, uint160[] memory secondsPerLiquidityCumulativeX128s) =
            IUniswapV3Pool(pool).observe(secondsAgos);
```

https://etherscan.io/address/0x8ad599c3A0ff1De082011EFDDc58f1908eb6e6D8#readContract

Try passing in 32, it works
Try passing in [32, 0] it reverts

<img width="1227" alt="confusion" src="https://user-images.githubusercontent.com/103224832/162980498-72935d40-3efb-4601-b3f7-cb3ff07e110f.png">
.

hm... I am having trouble getting this to work in Remix, unfortunately, even trying to replicate the Oracle code.

Is there any example contract which implements this price oracle?

**Comment by moodysalem** [comment]
pass in `32,0`, not `[32, 0]`

**Comment by Developer5600** [comment]
@moodysalem thank you.
How can I call this in solidity? I'm trying
```

import "https://raw.githubusercontent.com/Uniswap/v3-periphery/main/contracts/libraries/OracleLibrary.sol";

  function getEthPriceTick() public view returns (int24 arithmeticMeanTick, uint128 harmonicMeanLiquidity) {
    return OracleLibrary.consult(poolAddress(), 32);
  }
```

and still get an error
