### ISSUE TITLE
missing base64 contract

### ISSUE THREAD

**Issue by nuliknol** [Uniswap/v3-periphery#272]
Periphery contracts use some contract called `base64`. There is no reference anywhere about this contract and where to get the source of this contract (included inside file `NFTDescriptor.sol`)

`import 'base64-sol/base64.sol';`

 Some sources online exist, but the NFTDescriptor contract wont compile , returning this error:

 ```
 --> libraries/NFTSVG.sol:84:21:
   |
84 |                     bytes(
   |                     ^ (Relevant source part starts here and spans across multiple lines).

Error: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to string memory requested.
  --> libraries/NFTSVG.sol:94:21:
   |
94 |                     bytes(
   |                     ^ (Relevant source part starts here and spans across multiple lines).

Error: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to string memory requested.
   --> libraries/NFTSVG.sol:108:21:
    |
108 |                     bytes(
    |                     ^ (Relevant source part starts here and spans across multiple lines).

Error: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to string memory requested.
   --> libraries/NFTSVG.sol:123:21:
    |
123 |                     bytes(
    |                     ^ (Relevant source part starts here and spans across multiple lines).

Error: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to string memory requested.
  --> libraries/NFTDescriptor.sol:60:45:
   |

```
I am assuming that this error is due to incorrect base64 contract (that I found on some outdated repos) which returns string, but apparently the requirement is to return bytes. However since there are no sources I can't really be sure.

Please, provide reference to the source code for base64 contract since it doesn't exist anywhere. Thanks

**Comment by hensha256** [comment]
Hi! that contract is imported as a dependency [here](https://github.com/Uniswap/uniswap-v3-periphery/blob/22a7ead071fff53f00d9ddc13434f285f4ed5c7d/package.json#L36). You can see the NPM package [here](https://www.npmjs.com/package/base64-sol/v/1.0.1), and the github repo [here](https://github.com/Brechtpd/base64/blob/main/base64.sol).
