### ISSUE TITLE
Type error for @uniswap/v3-periphery/contracts/libraries/PoolAddress.sol on line 35

### ISSUE THREAD

**Issue by drm424** [Uniswap/v3-periphery#274]
When I compile the said contract with solidity versions >=0.8.0 I get the error:

TypeError: Explicit type conversion not allowed from "uint256" to "address".
--> .deps/npm/@uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:35:16:
|
35 | pool = address(
| ^ (Relevant source part starts here and spans across multiple lines).

**Comment by Graig123git** [comment]
@drm424 did you ever resolved this ?

**Comment by hensha256** [comment]
This is being fixed in #271

**Comment by hensha256** [comment]
Duplicate of #209
