### ISSUE TITLE
SwapRouter.sol not compiling in Remix

### ISSUE THREAD

**Issue by NickSneo** [Uniswap/v3-periphery#283]
When trying to compile [SwapRouter.sol](https://github.com/Uniswap/v3-periphery/blob/9ca9575d09b0b8d985cc4d9a0f689f7a4470ecb7/contracts/SwapRouter.sol) in Remix getting these errors - 
`Error: not found @openzeppelin/contracts/drafts/ERC20Permit.sol` in [TestERC20.sol](https://github.com/Uniswap/v3-periphery/blob/9ca9575d09b0b8d985cc4d9a0f689f7a4470ecb7/contracts/test/TestERC20.sol)
`Error: not found @openzeppelin/contracts/drafts/IERC20Permit.sol` in [SelfPermit.sol](https://github.com/Uniswap/v3-periphery/blob/9ca9575d09b0b8d985cc4d9a0f689f7a4470ecb7/contracts/base/SelfPermit.sol)

**Comment by hensha256** [comment]
Thats because Remix wont automatically perform your imports for you - you have to either copy those contracts in, or officially import them. If instead you clone the repo, you will find that it imports the contracts.
